- name: play level variables
  hosts: local
  connection: local # Ansible is connecting to localhost 
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HRS
    TRAINER: Siva
  tasks:
  - name: print course info
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"  
