- name: gather facts
  hosts: local
  connection: local
# ansible collects the info target server, before it execute any other task  
  tasks:
  - name: facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
    